version: '3.8'

services:
  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:staging
    container_name: frontend-staging
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=staging.devplayground.my.id
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
