version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:dev
    container_name: frontend-dev
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=dev.devplayground.my.id
      - LETSENCRYPT_HOST=dev.devplayground.my.id
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
