version: '3.8'

services:
  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:staging
    container_name: frontend-staging
    ports:
      - "8080:80"
    restart: always
