version: '3.8'

services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend-prod
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=devplayground.my.id,www.devplayground.my.id
      - LETSENCRYPT_HOST=devplayground.my.id,www.devplayground.my.id
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
